version: '3.1'

services:
  mysql:
    container_name: mysqlserver
    image: mysql:5.5
    network_mode: bridge
    volumes:
       - /storage/docker/mysql-datadir:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8989:3306"